#ifndef ORBIT_H
#define ORBIT_H

/* Generated by cbindgen from crates/orbit-ffi. Do not edit by hand. */

#include <stddef.h>
#include <stdint.h>

// Version of the native contract: C functions, JNI methods and the JSON
// protocol. Bumped on any incompatible change; the SDK refuses to start on a
// mismatch.
#define ORBIT_ABI_VERSION 2

#define ORBIT_OK 0

#define ORBIT_ERR_INVALID_ARGUMENT 1

#define ORBIT_ERR_INVALID_IDENTITY 2

#define ORBIT_ERR_STORAGE_LOCKED 3

#define ORBIT_ERR_IDENTITY_MISMATCH 4

#define ORBIT_ERR_STORAGE_KEY_MISMATCH 5

#define ORBIT_ERR_CORRUPTED 6

#define ORBIT_ERR_UNSUPPORTED_STORAGE_VERSION 7

#define ORBIT_ERR_NOT_FOUND 8

#define ORBIT_ERR_STORAGE 9

#define ORBIT_ERR_IO 10

#define ORBIT_ERR_RANDOM 11

#define ORBIT_ERR_CLOSED 12

#define ORBIT_ERR_BUSY 13

#define ORBIT_ERR_INTERNAL 14

#define ORBIT_ERR_WRONG_PASSCODE 15

// First byte of a passcode-locked identity secret; plain secrets start with 1.
#define ORBIT_IDENTITY_LOCKED_TAG 16

// Byte buffer allocated by Rust.
typedef struct OrbitBuffer {
  uint8_t *data;
  size_t len;
} OrbitBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Version of the native contract. See `ORBIT_ABI_VERSION`.
uint32_t orbit_abi_version(void);

// Generates a new identity secret for the platform secure store.
//
// # Safety
// `out_secret` must be a valid pointer to writable `OrbitBuffer` storage.
int32_t orbit_identity_generate(struct OrbitBuffer *out_secret);

// Seals an identity secret under a UTF-8 passcode (Argon2id). The result
// starts with `ORBIT_IDENTITY_LOCKED_TAG` and replaces the stored secret.
//
// # Safety
// Input pointers follow the module conventions; `out_locked` must be writable.
int32_t orbit_identity_lock(const uint8_t *secret,
                            size_t secret_len,
                            const uint8_t *passcode,
                            size_t passcode_len,
                            struct OrbitBuffer *out_locked);

// Opens a passcode-locked identity secret. Returns
// `ORBIT_ERR_WRONG_PASSCODE` when the passcode does not match.
//
// # Safety
// Input pointers follow the module conventions; `out_secret` must be writable.
int32_t orbit_identity_unlock(const uint8_t *locked,
                              size_t locked_len,
                              const uint8_t *passcode,
                              size_t passcode_len,
                              struct OrbitBuffer *out_secret);

// Opens the account described by `secret` in the directory from
// `config_json` (`{"data_dir": "/absolute/path"}`).
//
// # Safety
// Input pointers follow the module conventions; `out_engine` must be writable.
int32_t orbit_engine_open(const uint8_t *config_json,
                          size_t config_len,
                          const uint8_t *secret,
                          size_t secret_len,
                          uint64_t *out_engine);

// Queues a JSON command. The result arrives later as an event carrying the
// returned request ID.
//
// # Safety
// Input pointers follow the module conventions; `out_request_id` must be writable.
int32_t orbit_engine_submit(uint64_t engine,
                            const uint8_t *command_json,
                            size_t command_len,
                            uint64_t *out_request_id);

// Blocks up to `timeout_ms` (capped at 60 s) for events and writes
// `{"events":[...]}`. Returns `ORBIT_ERR_CLOSED` once the engine is closed.
//
// # Safety
// `out_events` must be a valid pointer to writable `OrbitBuffer` storage.
int32_t orbit_engine_wait_events(uint64_t engine,
                                 uint32_t timeout_ms,
                                 struct OrbitBuffer *out_events);

// Makes current `orbit_engine_wait_events` calls return an empty batch.
int32_t orbit_engine_cancel_wait(uint64_t engine);

// Closes the engine, wakes waiters and returns after the worker stopped.
// Closing an already closed handle succeeds.
int32_t orbit_engine_close(uint64_t engine);

// Wipes and releases a buffer returned by this library. Null data is ignored.
//
// # Safety
// `buffer` must come from this library and must not be used or freed again.
void orbit_buffer_free(struct OrbitBuffer buffer);

// Copies the message of the last failed call on this thread.
//
// # Safety
// `out_message` must be a valid pointer to writable `OrbitBuffer` storage.
int32_t orbit_last_error_message(struct OrbitBuffer *out_message);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ORBIT_H */
